name: django app

on: [push]

jobs:
    build:
        
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v1
            - name: hello world
              run: |
                echo "hello world" 
